rancher/rancher-turtles-e2e

- .github/workflows/master-e2e.yaml
- tests/cypress/latest/e2e/unit_tests/turtles_plugin.spec.ts
Fixes Turtles UI title changes
https://github.com/rancher-sandbox/rancher-turtles-e2e/actions/runs/7722867871
> Turtles UI title fix

- tests/cypress/latest/e2e/unit_tests/turtles_plugin.spec.ts
Since we are only using dev UI version, disabled the stable version check
Fixes: Failing CI https://github.com/rancher-sandbox/rancher-turtles-e2e/actions/runs/7809820748
https://github.com/rancher-sandbox/rancher-turtles-e2e/actions/runs/7811604011
> Change extensions repo setting

- tests/cypress/latest/e2e/unit_tests/capd_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/namespace.spec.ts
Add fixes for failing CI tests related to timeout and page refresh.
v2.7: https://github.com/rancher-sandbox/rancher-turtles-e2e/actions/runs/8154166931
v2.8: https://github.com/rancher-sandbox/rancher-turtles-e2e/actions/runs/8153872056
> Fix flaky CI tests

- README.md
- tests/cypress/latest/e2e/unit_tests/capd_cluster.spec.ts
- tests/cypress/latest/support/commands.ts
- tests/cypress/latest/support/e2e.ts
This PR adds cluster deletion test and updates README with instructions to run the tests locally.
Fixes #
> Add Deletion test and update readme

- .github/workflows/master-e2e.yaml
- README.md
- tests/cypress/latest/e2e/unit_tests/capd_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capd_setup.spec.ts
- tests/cypress/latest/e2e/unit_tests/turtles_operator.spec.ts
- tests/cypress/latest/support/commands.ts
- tests/cypress/latest/support/e2e.ts
1. Added tests for CAPD cluster:
- Import by cluster annotation
- Scale imported cluster
- Remove imported cluster
2. Cypress function for common operations
3. New runner template
Fixes: https://github.com/rancher/highlander/issues/64
https://github.com/rancher-sandbox/rancher-turtles-e2e/actions/runs/8572604031
> Added automation for CAPD tests

- tests/cypress/latest/e2e/unit_tests/capa_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capd_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/menu.spec.ts
- tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
- tests/cypress/latest/support/commands.ts
- Fixes for new extension version
- Updated logic to check scaling
- Removed duplicate assertions
https://github.com/rancher/rancher-turtles-e2e/actions/runs/8848433502
> Fixes for new extension version

- tests/assets/rancher-turtles-fleet-example/rke2_namespace_autoimport/clusters/cluster1.yaml
- tests/cypress/latest/e2e/unit_tests/capd_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
- tests/cypress/latest/e2e/unit_tests/turtles_operator.spec.ts
- tests/cypress/latest/e2e/unit_tests/turtles_plugin.spec.ts
- tests/cypress/latest/support/commands.ts
- Add retries for installApp, addRepository
- Adjust timeouts as per defaultCommandTimeout
- Fix flaky checks
- GitHub Actions:
https://github.com/rancher/rancher-turtles-e2e/actions/runs/9468769539
> Add retry and fix flaky tests

- tests/cypress/latest/support/commands.ts
Adds check to ensure elements are loaded on page for further checks
https://github.com/rancher/rancher-turtles-e2e/actions/runs/9565006551
> Add check for provider deletion

- .github/workflows/master-e2e.yaml
- .github/workflows/ui-rm_head_2.8.yaml
- tests/cypress/latest/e2e/unit_tests/capa_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capd_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/first_connection.spec.ts
- Fixes cluster name due to v1>v3 migration
- Changes Rancher default password to more secure one
Fixes #39 , Failing CI
https://github.com/rancher/rancher-turtles-e2e/actions/runs/9691085719
> Fix cluster name & change default password

- tests/cypress/latest/e2e/unit_tests/capa_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capd_cluster.spec.ts
- tests/cypress/latest/support/commands.ts
- tests/cypress/latest/support/e2e.ts
- Refactors cluster deletion scenarios due to turtles/issues/589
- Adds new functions for common operations
https://github.com/rancher/rancher-turtles-e2e/actions/runs/9826707575
> Fix Cluster Removal TCs

- .github/workflows/master-e2e.yaml
- tests/assets/rancher-turtles-fleet-example/clusterclass_autoimport/classes/fleet.yaml
- tests/assets/rancher-turtles-fleet-example/clusterclass_autoimport/classes/quickstart.yaml
- tests/assets/rancher-turtles-fleet-example/clusterclass_autoimport/clusters/cluster1.yaml
- tests/assets/rancher-turtles-fleet-example/clusterclass_autoimport/clusters/fleet.yaml
- tests/cypress/latest/e2e/unit_tests/capa_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capd_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capd_clusterclass.spec.ts
- tests/cypress/latest/support/commands.ts
- tests/cypress/latest/support/e2e.ts
Adds tests for https://github.com/rancher-sandbox/rancher-turtles-fleet-example/tree/clusterclass branch
Fixes #47 
https://github.com/rancher/rancher-turtles-e2e/actions/runs/10124653143
> CAPD clusterclass branch tests

- tests/cypress/latest/e2e/unit_tests/capd_cluster.spec.ts
Skip deletion check for CAPD-RKE2
:green_circle: https://github.com/rancher/rancher-turtles-e2e/actions/runs/10523884520
> Skip deletion check

- .github/workflows/master-e2e.yaml
- tests/scripts/deploy-chartmuseum
Fixes part building turtles chart and image
> Adapt variables for image naming according to upstream PR#740

- .github/workflows/master-e2e.yaml
- tests/scripts/deploy-chartmuseum
Adapt the chart filename to the change in upstream
> Fix helm chart name according to PR#748

- .github/workflows/master-e2e.yaml
- .github/workflows/ui-e2e.yaml
- tests/cypress/latest/e2e/unit_tests/capa_eks_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capa_rke2_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capd_kubeadm_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capd_rke2_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/first_connection.spec.ts
- tests/cypress/latest/e2e/unit_tests/menu.spec.ts
- tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
- tests/cypress/latest/e2e/unit_tests/turtles_operator.spec.ts
- tests/cypress/latest/e2e/unit_tests/turtles_plugin.spec.ts
- tests/cypress/latest/e2e/unit_tests/user.spec.ts
- tests/cypress/latest/package.json
- tests/cypress/latest/support/commands.ts
- tests/e2e/suite_test.go
- tests/go.mod
- tests/go.sum
- Align QASE id's with tests
- Modifies run-name for dispatched runs with detailed information
- Remove elemental references
Run-name:
Fixes #63 
https://github.com/rancher/rancher-turtles-e2e/actions/runs/11036032672
Qase public report:
https://app.qase.io/public/report/c594df334f8549263d26defbdbda8cf511482e81
CAAPF IDs yet to be added
> Align QASE IDs with tests

- tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
Checks fleetProvider name and Ready status
https://github.com/rancher/rancher-turtles-e2e/actions/runs/11361116544
> Fix fleetProvider name

- .github/workflows/janitor.yaml
Move from rancher-sandbox/aws-janitor to rancher/aws-janitor
Fixes - Failing job https://github.com/rancher/rancher-turtles-e2e/actions/runs/11452579849
> Update aws-janitor repo

- tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
Bumps GKE provider version
https://github.com/rancher/rancher-turtles-e2e/actions/runs/11555177316
> Update GCP provider version

- tests/cypress/latest/e2e/unit_tests/capa_eks_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capa_rke2_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capd_kubeadm_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capd_rke2_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capz_cluster.spec.ts
- tests/cypress/latest/support/commands.ts
- tests/cypress/latest/support/e2e.ts
Refactors checking fleet repo status due UI loading issue.
Short: https://github.com/rancher/rancher-turtles-e2e/actions/runs/11717538923
Full: https://github.com/rancher/rancher-turtles-e2e/actions/runs/11717536442
> Refactor FleetRepo check

- tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
Updates local provider versions w.r.t upcoming turtles November release
https://github.com/rancher/rancher-turtles-e2e/actions/runs/12080779506
Cloud providers version to be bumped in separate PR.
> Update local provider versions

- .github/workflows/master-e2e.yaml
- tests/assets/rancher-turtles-fleet-example/gcp_gke/clusters/cluster1.yaml
- tests/assets/rancher-turtles-fleet-example/gcp_gke/clusters/fleet.yaml
- tests/cypress/latest/e2e/unit_tests/capg_cluster.spec.ts
Adds CAPG to full suite
Fixes #84 
https://github.com/rancher/rancher-turtles-e2e/actions/runs/12183588312
(Ran on this PR branch)
> Automate CAPG

- .github/workflows/master-e2e.yaml
Adapts image build process as per turtles repo change https://github.com/rancher/turtles/pull/902
https://github.com/rancher/rancher-turtles-e2e/actions/runs/12196990836
> Change docker-build for local e2e image

- tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
> Kubeadm version bump; fix docker test failure

- tests/cypress/latest/e2e/unit_tests/turtles_operator.spec.ts
- tests/cypress/latest/support/commands.ts
Fix installApp params as per [e2e.ts](https://github.com/rancher/rancher-turtles-e2e/blob/main/tests/cypress/latest/support/e2e.ts#L29)
Fixes - Nightly CI
`@install @short` nightly - https://github.com/rancher/rancher-turtles-e2e/actions/runs/12784563423
`@install` v0.15.0 - https://github.com/rancher/rancher-turtles-e2e/actions/runs/12784596754
> Fix installApp params

- tests/assets/rancher-turtles-fleet-example/gcp_gke/clusters/cluster1.yaml
- tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
- tests/cypress/latest/e2e/unit_tests/turtles_operator.spec.ts
Full suite fixes
https://github.com/rancher/rancher-turtles-e2e/actions/runs/12923596571
CAPZ failure expected due to turtles/issues/990
> Full suite fixes

- .github/workflows/master-e2e.yaml
- .github/workflows/ui-e2e.yaml
- tests/cypress/latest/e2e/unit_tests/capa_eks_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capa_rke2_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capd_kubeadm_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capd_rke2_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capg_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capz_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
- tests/cypress/latest/e2e/unit_tests/turtles_operator.spec.ts
- tests/cypress/latest/support/commands.ts
- tests/cypress/latest/support/e2e.ts
- Automates Qase TC 41
- Renaming for correct denotation: `App to Chart, nightly to dev`
Fixes #
- https://github.com/rancher/rancher-turtles-e2e/actions/runs/13118546906
- https://github.com/rancher/rancher-turtles-e2e/actions/runs/13119703385, Nightly true
> Refactor installApp & automate update chart

- .github/workflows/master-e2e.yaml
- .github/workflows/ui-e2e.yaml
- tests/cypress/latest/e2e/unit_tests/turtles_plugin.spec.ts
Adds Input to select CAPI-UI Extension version
Fixes #106 
https://github.com/rancher/rancher-turtles-e2e/actions/runs/13193586615 (Default: latest)
https://github.com/rancher/rancher-turtles-e2e/actions/runs/13193590336 (Version: 0.8.1)
> Add Input to select CAPI-UI Extension version

- tests/assets/rancher-turtles-fleet-example/azure/azure-capz-helmchart/templates/azure-clusterclass.yaml
- tests/cypress/latest/e2e/unit_tests/capd_clusterclass_ui_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capz_cluster.spec.ts
- tests/cypress/latest/fixtures/capz-helm-values.yaml
- tests/cypress/latest/support/commands.ts
- tests/cypress/latest/support/e2e.ts
Adds CAPZ cluster from ClusterClass UI
Fixes #115 
https://github.com/rancher/rancher-turtles-e2e/actions/runs/13417196048
(Ran on `class-capz` branch, only Install App TC failed)
> CAPZ cluster from ClusterClass UI

- tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
kubeadm and fleet providers bump
> Bump kubeadm and fleet providers

- tests/cypress/latest/e2e/unit_tests/capv_rke2_cluster.spec.ts
Use rancher repo instead my fork for capv
> Use rancher repo for capv tests

- .github/workflows/ui-e2e.yaml
> Make scheduled jobs unique

- .github/workflows/ui-e2e.yaml
Attempt to fix nightly job startup failure
https://github.com/rancher/rancher-turtles-e2e/actions/runs/13983823170
> Fix skip_cluster_delete input for scheduled jobs

- tests/cypress/latest/e2e/unit_tests/capa_eks_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capa_rke2_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capd_clusterclass_ui_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capd_kubeadm_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capd_rke2_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capg_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capv_rke2_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capz_cluster.spec.ts
- tests/cypress/latest/plugins/index.ts
- tests/cypress/latest/support/utils.ts
This is a followup fix when Cluster Delete is set to false.
Fixes #137
> Fix Delete cluster option

- tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
Bump provider versions w.r.t turtles v0.18.0-rc.0
> Bump provider versions

- tests/cypress/latest/e2e/unit_tests/capd_rke2_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
Re-enables tests CAAPF tests w.r.t latest turtles release
Fixes #
https://github.com/rancher/rancher-turtles-e2e/actions/runs/14188196680
> Re-enable CAAPF tests

- tests/cypress/latest/e2e/unit_tests/capv_rke2_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
- tests/cypress/latest/support/commands.ts
- tests/cypress/latest/support/e2e.ts
* Better handling of App installation - it waits until all the repos are refreshed and if the app is still not present in the list it keeps refreshing repos until it is present
* Waiting for successful App installation or update, added state checks of the deployed application
* New cy function `waitForAllRowsInState` for waiting until all listed resources in a table are in desired state
* Explicit waits here and there, some timeouts were added, other prolonged
* Custom Fleet-addon configuration is temporary skipped and fleet-agent is installed on all downstream clusters automatically
Fixes #149
* ✅ short https://github.com/rancher/rancher-turtles-e2e/actions/runs/14357440440
* ✅ vsphere https://github.com/rancher/rancher-turtles-e2e/actions/runs/14357448812
* ☑️ full …
> Apps installation and repos handling improvements

- tests/cypress/latest/e2e/unit_tests/turtles_operator.spec.ts
- tests/cypress/latest/support/commands.ts
> Remove checking Enable Agent TLS Mode; it is now enabled by default

- .github/workflows/master-e2e.yaml
- tests/assets/rancher-turtles-fleet-example/capa/eks/clusters/Chart.yaml
- tests/assets/rancher-turtles-fleet-example/capa/rke2/class-clusters/Chart.yaml
- tests/assets/rancher-turtles-fleet-example/capd/kubeadm/class-clusters/Chart.yaml
- tests/assets/rancher-turtles-fleet-example/capd/kubeadm/clusters/Chart.yaml
- tests/assets/rancher-turtles-fleet-example/capd/rke2/class-clusters/Chart.yaml
- tests/assets/rancher-turtles-fleet-example/capd/rke2/clusters/Chart.yaml
- tests/assets/rancher-turtles-fleet-example/capg/gke/clusters/Chart.yaml
- tests/assets/rancher-turtles-fleet-example/capv/rke2/class-clusters/.helmignore
- tests/assets/rancher-turtles-fleet-example/capv/rke2/class-clusters/Chart.yaml
- tests/assets/rancher-turtles-fleet-example/capv/rke2/class-clusters/fleet.yaml
- tests/assets/rancher-turtles-fleet-example/capv/rke2/class-clusters/templates/cluster.yaml
- tests/assets/rancher-turtles-fleet-example/capv/rke2/class-clusters/values.yaml
- tests/assets/rancher-turtles-fleet-example/capv/rke2/clusters/values.yaml
- tests/cypress/latest/e2e/unit_tests/capv_rke2_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capv_rke2_clusterclass.spec.ts
- tests/cypress/latest/fixtures/capv-vsphere-cluster-identity.yaml
- tests/cypress/latest/support/commands.ts
- tests/cypress/latest/support/e2e.ts
Add CAPV RKE2 Clusterclass tests
Fixes #165 
https://github.com/rancher/rancher-turtles-e2e/actions/runs/15014132194
> CAPV RKE2 Clusterclass

- .github/workflows/master-e2e.yaml
- tests/assets/rancher-turtles-fleet-example/capa/rke2/clusters/.helmignore
- tests/assets/rancher-turtles-fleet-example/capa/rke2/clusters/Chart.yaml
- tests/assets/rancher-turtles-fleet-example/capa/rke2/clusters/fleet.yaml
- tests/assets/rancher-turtles-fleet-example/capa/rke2/clusters/templates/cluster.yaml
- tests/cypress/latest/e2e/unit_tests/capa_rke2_cluster.spec.ts
Re-adds AWS RKE2 cluster test using HelmApps
Fixes #
https://github.com/rancher/rancher-turtles-e2e/actions/runs/15273367677
> Add AWS RKE2 Cluster tests

- .github/workflows/master-e2e.yaml
- tests/assets/rancher-turtles-fleet-example/capa/kubeadm/clusters/.helmignore
- tests/assets/rancher-turtles-fleet-example/capa/kubeadm/clusters/Chart.yaml
- tests/assets/rancher-turtles-fleet-example/capa/kubeadm/clusters/fleet.yaml
- tests/assets/rancher-turtles-fleet-example/capa/kubeadm/clusters/templates/cluster.yaml
- tests/assets/rancher-turtles-fleet-example/capv/kubeadm/class-clusters/values.yaml
- tests/cypress/latest/e2e/unit_tests/capa_kubeadm_cluster.spec.ts
Adds AWS Kubeadm Cluster tests
https://github.com/rancher/rancher-turtles-e2e/actions/runs/15319041365
> AWS Kubeadm Cluster tests

- .github/workflows/master-e2e.yaml
- tests/assets/rancher-turtles-fleet-example/capz/kubeadm/class-clusters/.helmignore
- tests/assets/rancher-turtles-fleet-example/capz/kubeadm/class-clusters/Chart.yaml
- tests/assets/rancher-turtles-fleet-example/capz/kubeadm/class-clusters/fleet.yaml
- tests/assets/rancher-turtles-fleet-example/capz/kubeadm/class-clusters/templates/cluster.yaml
- tests/cypress/latest/e2e/unit_tests/capz_kubeadm_clusterclass.spec.ts
> Azure kubeadm clusterclass test

- .github/workflows/master-e2e.yaml
- tests/cypress/latest/e2e/unit_tests/capz_rke2_v2prov_cluster.spec.ts
- tests/cypress/latest/fixtures/azure-rke-config.yaml
- tests/cypress/latest/fixtures/azure-rke2-cluster.yaml
- tests/cypress/latest/support/commands.ts
- tests/cypress/latest/support/e2e.ts
Adds Azure RKE2 v2Prov test to the full suite.
Cluster template used: https://github.com/rancher/turtles/blob/main/test/e2e/data/rancher/azure-cluster.yaml
Fixes #
https://github.com/rancher/rancher-turtles-e2e/actions/runs/15729087463
> Azure RKE2 v2Prov test

- tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
Bump fleetProviderVersion ahead of Turtles June RC
Fixes - Failing nightly CI
> Bump fleetProviderVersion

- .github/workflows/master-e2e.yaml
I updated cypress module in https://github.com/rancher/rancher-turtles-e2e/pull/217 but forgot about container.
> Update CYPRESS_DOCKER image

- tests/cypress/latest/e2e/unit_tests/capd_ui_clusterclass.spec.ts
- tests/cypress/latest/e2e/unit_tests/capg_gke_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capg_kubeadm_clusterclass.spec.ts
- tests/cypress/latest/e2e/unit_tests/capv_kubeadm_clusterclass.spec.ts
- tests/cypress/latest/e2e/unit_tests/capv_rke2_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capv_rke2_clusterclass.spec.ts
- tests/cypress/latest/e2e/unit_tests/capz_rke2_v2prov_cluster.spec.ts
- tests/cypress/latest/support/capz_support.ts
- tests/cypress/latest/support/commands.ts
- tests/cypress/latest/support/e2e.ts
- Rename `importYaml` to `importYAML`.
- Change the function signature from `importYaml(clusterName, yamlOrPath, namespace)` to `importYAML(yamlOrPath, namespace, clusterName='local')`
- Refactor the code to use the function.
Fixes part of #152
> Use the common function importYAML

- tests/assets/rancher-turtles-fleet-example/capz/rke2/class-clusters/fleet.yaml
- tests/assets/rancher-turtles-fleet-example/capz/rke2/class-clusters/templates/cluster.yaml
- tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
> Remove registration-method variable from CAPZ

- tests/assets/rancher-turtles-fleet-example/capd/kubeadm/class-clusters/fleet.yaml
- tests/assets/rancher-turtles-fleet-example/capd/kubeadm/class-clusters/templates/cluster.yaml
- tests/assets/rancher-turtles-fleet-example/capd/rke2/class-clusters/fleet.yaml
- tests/assets/rancher-turtles-fleet-example/capd/rke2/class-clusters/templates/cluster.yaml
- tests/cypress/latest/e2e/capd_kubeadm_clusterclass.spec.ts
- tests/cypress/latest/e2e/capd_rke2_clusterclass.spec.ts
- tests/cypress/latest/e2e/capg_kubeadm_clusterclass.spec.ts
- tests/cypress/latest/fixtures/capd-helm-values.yaml
Refactor CAPD scaling tests for class-clusters, using [capv](https://github.com/rancher/rancher-turtles-e2e/blob/main/tests/cypress/latest/e2e/legacy/capv_rke2_cluster.spec.ts#L124) method.
Fixes part of https://github.com/rancher/rancher-turtles-e2e/issues/224
:green_circle: https://github.com/rancher/rancher-turtles-e2e/actions/runs/16437402047
> Refactor CAPD scaling tests

- .github/workflows/master-e2e.yaml
- .github/workflows/ui-e2e.yaml
- Use docker login using PAT, to mitigate docker pull rate limit
Fixes #
https://github.com/rancher/rancher-turtles-e2e/actions/runs/16797528931
(failures unrelated)
> Use docker login

- .github/workflows/ui-e2e.yaml
- tests/cypress/latest/e2e/capd_kubeadm_ui_clusterclass.spec.ts
- tests/cypress/latest/e2e/capd_rke2_clusterclass.spec.ts
- tests/cypress/latest/e2e/capd_rke2_fleet_clusterclass.spec.ts
- tests/cypress/latest/e2e/capd_rke2_upgrade_clusterclass.spec.ts
- tests/cypress/latest/e2e/providers_setup.spec.ts
- tests/cypress/latest/support/cleanup_support.ts
Adds CI job for chart upgrade tests
Fixes #253 
https://github.com/rancher/rancher-turtles-e2e/actions/runs/17318704168/job/49166910456
(InstallApp failure)
> Upgrade chart CI job

- tests/cypress/latest/e2e/providers_setup.spec.ts
Bump Provider versions for dev
Fixes #
:green_circle: [@vsphere](https://github.com/rancher/rancher-turtles-e2e/actions/runs/17548519006), [@short](https://github.com/rancher/rancher-turtles-e2e/actions/runs/17548488063),
[@full](https://github.com/rancher/rancher-turtles-e2e/actions/runs/17549267172) (running)
> Bump Providers

- tests/cypress/latest/support/commands.ts
Add turtles-chart selector for installation.
Fixes #
:green_circle: `@install`
[2.11](https://github.com/rancher/rancher-turtles-e2e/actions/runs/17855002098), [2.12](https://github.com/rancher/rancher-turtles-e2e/actions/runs/17854995639)
> Add turtles-chart selector

- tests/cypress/latest/e2e/providers_setup.spec.ts
bumped kubeadm to v1.10.6 for dev builds
> Bump kubeadm version
