- .github/workflows/master-e2e.yaml
We would like to use the same GCP disk for Elemental and Turtles.
The disk is `qa-e2e-ci-runner-x86-64-image-v1`
> Add variables to use the same GCP disk

- .github/workflows/master-e2e.yaml
- tests/cypress/latest/e2e/unit_tests/namespace.spec.ts
PR adds test scenario for checking and enabling default namespace CAPI auto-import
Verification run: https://github.com/rancher-sandbox/rancher-turtles-e2e/actions/runs/7186100168/job/19570797884
> Added test for enabling namespace auto-import

- tests/cypress/latest/e2e/unit_tests/namespace.spec.ts
Disabling a check due to bug in Rancher 2.7
> Update namespace test for v2.7

- tests/cypress/latest/e2e/unit_tests/capd_cluster.spec.ts
On fleet page, sometimes default fleet namespace in dropdown is set 'fleet-default' or 'fleet-local'. These changes selects correct namespace for our tests
https://github.com/rancher-sandbox/rancher-turtles-e2e/actions/runs/7271804657
> Fleet namespace CI fix

- tests/cypress/latest/e2e/unit_tests/turtles_plugin.spec.ts
Fixes locator for CAPI Extension Install button for different Rancher releases
2.7: https://github.com/rancher-sandbox/rancher-turtles-e2e/actions/runs/7828769313
2.8: https://github.com/rancher-sandbox/rancher-turtles-e2e/actions/runs/7828770514
> Fix CAPI extension Install button

- tests/cypress/latest/e2e/unit_tests/capd_setup.spec.ts
- tests/cypress/latest/fixtures/capi-kubeadm-provider.yaml
With change introduced in https://github.com/rancher/turtles/pull/402, need to enable kubeadm provider explicitly.
Fixes: Failing CI tests
https://github.com/rancher-sandbox/rancher-turtles-e2e/actions/runs/8281244103
> Enable capi-kubeadm-provider

- .github/workflows/janitor.yaml
- tests/assets/rancher-turtles-fleet-example/aws/clusters/cluster1.yaml
Updates AWS region for creating CAPI cluster and Enable janitor for the region, to avoid CI failures due to lack of resources eg. https://github.com/rancher-sandbox/rancher-turtles-e2e/actions/runs/8810903401
> Update AWS region and enable janitor

- tests/cypress/latest/e2e/unit_tests/capa_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capd_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/menu.spec.ts
- tests/cypress/latest/support/commands.ts
- tests/cypress/latest/support/e2e.ts
Due to new UI changes, added a check to make sure CAPI Menu is visible
Fixes - Cluster deletion assertion check
https://github.com/rancher/rancher-turtles-e2e/actions/runs/8876151687
> Add CAPIMenu check

- .github/workflows/master-e2e.yaml
- tests/assets/rancher-turtles-fleet-example/rke2_namespace_autoimport/clusters/cluster1.yaml
- tests/assets/rancher-turtles-fleet-example/rke2_namespace_autoimport/clusters/fleet.yaml
* bump of GCP template to `capi-e2e-ci-runner-spot-n2-highmem-16-template-v2` based on opensuse 15.6 with by-default enabled `cgroup2fs`, see https://kubernetes.io/docs/concepts/architecture/cgroups/
* upstream k3s bumped to `v1.28.11+k3s1`
* rke2-docker bumped to `v1.28.9+rke2r1` -  there is a bug that k8s version patch level cannot contains 2 digits
* rke2-docker - ignore modified resources by CAPI in fleet gitrepo
Fixes #44 
(unrealted failure when deleting clusters - they are getting recreated for some reason)
> New GCP template based on 15.6 with cgroupfs enabled to make RKE2-v1.28 work

- tests/go.mod
- tests/go.sum
Part of https://github.com/rancher/hosted-providers-e2e/issues/149
`rancher/rancher:v2.8-head` from dockerhub is outdated, this is about bumping ele-testhelpers which is already using correct image from stgregistry.
testrun: https://github.com/rancher/rancher-turtles-e2e/actions/runs/10416784510 (rancher provisioning passed)
> Bump ele-testhelpers to use v2.8-head from stgregistry

- .github/workflows/master-e2e.yaml
- .github/workflows/ui-e2e.yaml
- tests/Makefile
Mainly borrowed from fleet-e2e where I've implemented this originally
* Brings new input field for github actions where you can enter `auto` (default), `none` or `existing_qase_run_id`.
`auto`	... uses next available qase_run_id (default)
`none`	... no report created
`run_id` 	... overrides existing qase test run report
* setup-go action now configured to use cache on `ubuntu-latest` gh runners and disabled cache on gcp runner = less warnings
* changed also few more consmetic things like public_ip/dns, Makefile, added a new job `declare-cancelled`, ...
Fixes # https://github.com/rancher/rancher-turtles-e2e/issues/46
Testruns:
https://github.com/rancher/rancher-turtles-e2e/actions/runs/10558865241 for `none` (and cancelled)
https://github.com/rancher/rancher-turtles-e2e/actions/runs/1055894 …
> Qase reporting improvements and handling GO cache

- tests/e2e/suite_test.go
Fixes issue when running CI against `prime/2.9.1` is failing on `index out of range` error. The code was originally designed for `latest/devel/2.9` and not for `latest/2.9.0` nor `prime/2.9.1` which are supported by ele-testhelpers.
Failure for `prime/2.9.1`: https://github.com/rancher/rancher-turtles-e2e/actions/runs/10578000973/job/29307217653
Testrun: https://github.com/rancher/rancher-turtles-e2e/actions/runs/10578590235
> Add support for stable rancher versions like prime/2.9.1 or latest/2.9.0

- .github/workflows/master-e2e.yaml
There was about 8000 Managed Secrets on GCP created by various GCP runners which costs money.
This PR will set Expiration time by `--ttl=36000s` for newly created secrets so they will be auto removed after 10h.
> Set expiration time for GCP runner secrets

- tests/go.mod
- tests/go.sum
Testrun: https://github.com/rancher/rancher-turtles-e2e/actions/runs/11689526220
> Bump ele-testhelpers to support v2.10-head and new location for v2.9-head

- .github/workflows/master-e2e.yaml
Bump k3s version as new CAPI UI 0.7.0 is already compatible with 1.30.x
Ref. https://github.com/rancher/capi-ui-extension/issues/84
Testrun: https://github.com/rancher/rancher-turtles-e2e/actions/runs/11689436994
> Bump k3s version to v1.30.6+k3s1

- .github/workflows/master-e2e.yaml
- .github/workflows/ui-e2e.yaml
- tests/cypress/latest/e2e/unit_tests/turtles_operator.spec.ts
Add option to select nightly/stable rancher turtles chart  and Set qase_run_id default to none
Fixes #
> Add option to select nightly/stable rancher turtles chart  and Set qase_run_id default to none

- tests/assets/rancher-turtles-fleet-example/rke2_clusterclass_autoimport/classes/quickstart.yaml
- tests/assets/rancher-turtles-fleet-example/rke2_namespace_autoimport/clusters/cluster1.yaml
Makes capd rke2 tests work on capi/capd 1.9+
Related code: `https://github.com/rancher/turtles/pull/961/files#diff-2ec716dc6284543a12fd427cc46b7efff72a43e217b473209caf237e59902eb2`
WARNING: It is not backward compatible so it won't work with released/stable turtles v0.15.0
Both cases for clusterclass and standalone cluster tested locally only:
> Adapt RKE2 resources to be compatible with CAPI 1.9+

- tests/cypress/latest/e2e/unit_tests/turtles_operator.spec.ts
Fleet-addon is now enabled by default while installation. Ref: turtles/pull/1004
Fixes - Nightly CI
https://github.com/rancher/rancher-turtles-e2e/actions/runs/12804611944
> Update caapf enablement

- tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
- tests/cypress/latest/e2e/unit_tests/turtles_operator.spec.ts
- tests/cypress/latest/plugins/index.ts
~Use different versions of the fleet provider for nightly and stable runs. The version is determined by the presence of the `chartmuseum_repo` string, which indicates a nightly build.~
Reverting back to hardcoded version approach as the nightly and stable versions are in sync now.
Fixes #
~* https://github.com/rancher/rancher-turtles-e2e/actions/runs/13049910755 nightly~
~* https://github.com/rancher/rancher-turtles-e2e/actions/runs/13049924421 stable~
* (hardcoded) nightly=false https://github.com/rancher/rancher-turtles-e2e/actions/runs/13051155539
> Different versions of fleet provider for nightly and stable

- .github/workflows/master-e2e.yaml
Better turtles + ui version reporting in gh run summary
nightly: https://github.com/rancher/rancher-turtles-e2e/actions/runs/13048493540
stable: https://github.com/rancher/rancher-turtles-e2e/actions/runs/13048498019
~I also removed `capi_ui_version` variable and related function which is not in use and I don't see any use case for that.~
Fixes #
* `@short stable` https://github.com/rancher/rancher-turtles-e2e/actions/runs/13052850388
> Report Turtles and CAPI UI versions

- tests/cypress/latest/e2e/unit_tests/capd_kubeadm_cluster.spec.ts
- tests/cypress/latest/support/commands.ts
- tests/cypress/latest/support/e2e.ts
ref. https://github.com/rancher/rancher-turtles-e2e/issues/111
borrowed few lines from fleet-e2e, 2 new caapf tests implemented, qase cases were created as RT-42 and RT-43
* checks whether the capi cluster is registered only once under CD/Fleet/Clusters
* check whether v3 annotation for externally-provisioned cluster is set in Cluster management/Clusters
The annotation should be automatically added into clusters provisioned by upcoming R 2.10.3 or 2.10-head via dev turtles.
> Add checks for fleet-addon provider

- tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
Configuration for fleet-agent to use `hostNetwork` is not needed anymore as it become default.
Fixes https://github.com/rancher/rancher-turtles-e2e/issues/101
> Do not set hostNetwork in fleet-addon-config

- .github/workflows/master-e2e.yaml
Fixes dependency for `post-qase` job - it couldn't use gcp runner which has been deleted already
As result the action was stuck on waiting for runner which didn't exist anymore, see https://github.com/rancher/rancher-turtles-e2e/actions/runs/13667632831
Fixes #
> Fix post-qase runner selection

- .github/workflows/master-e2e.yaml
using `ubuntu-latest` runners for `post/pre-qase` and `declare-canceled` jobs to simplify
Fixes #127 
* vsphere (qase_id=auto and cancelled) https://github.com/rancher/rancher-turtles-e2e/actions/runs/13718061397
* short (qase_id=auto and cancelled) https://github.com/rancher/rancher-turtles-e2e/actions/runs/13718038999
for deleting qase_run_id after cancel in qase we probably don't have needed permissions:
> Use ubuntu-latest for independent steps

- tests/cypress/latest/support/commands.ts
Sometimes happens that no Application is displayed on `Featured Chart` page, esp. on vsphere clusters (maybe due to its geo location?) so the entire test is failing on installing `Monitoring` app. This PR should resolve that by refreshing all existing app repos prior installing.
Fixes #124
> Refresh repos before installing App

- tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
New fleet addon provider released for nightly turtles.
Also the version is not hardcoded anymore in the check line but using extra const (+same for vsphereProvider)
> Bump fleetProviderVersion

- .github/workflows/master-e2e.yaml
- .github/workflows/ui-e2e.yaml
- tests/cypress/latest/e2e/unit_tests/capa_eks_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capa_rke2_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capd_clusterclass_ui_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capd_kubeadm_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capd_rke2_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capg_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capv_rke2_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capz_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
- tests/cypress/latest/plugins/index.ts
- tests/cypress/latest/support/utils.ts
- tests/scripts/start-cypress-tests
1. This PR attempts to skip cluster deletion for cloud providers. This fix will be implemented for CAPD after #130 is done.
2. Separate cloud provider namespace creation so that they are created with proper tags. (Earlier when I tried to run CI job with `@install @full` tags, cloud provider namespaces were not created and the subsequent tests failed).
Fixes #94
> Add option not to delete cluster for Cloud Providers

- tests/cypress/latest/e2e/unit_tests/capd_rke2_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
- Skips tests due to `turtles/issues/1219`
- Bumps fleet-addon version
Fixes - Nightly CI
https://github.com/rancher/rancher-turtles-e2e/actions/runs/14105940630
> Temporarily skip fleet-addon related tests

- .github/workflows/master-e2e.yaml
This PR removes the need for create-runner job to succeed and the dependency on e2e job for delete runner to get triggered.
The runner must be removed if the job has been cancelled.
Fixes #
> Delete the GCP runner if the job has been cancelled

- .github/workflows/master-e2e.yaml
- tests/cypress/latest/e2e/unit_tests/capd_kubeadm_cluster.spec.ts
- tests/cypress/latest/support/commands.ts
Fix turtles installation on 2.11. The new fix works for both 2.10 and 2.11.
Fixes #142
> Add support for 2.11

- .github/workflows/master-e2e.yaml
- README.md
- tests/cypress/latest/e2e/unit_tests/capa_eks_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capa_rke2_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capd_clusterclass_ui_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capd_kubeadm_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capd_rke2_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capg_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capz_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/first_connection.spec.ts
- tests/cypress/latest/e2e/unit_tests/menu.spec.ts
- tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
- tests/cypress/latest/e2e/unit_tests/turtles_extension.spec.ts
- tests/cypress/latest/e2e/unit_tests/turtles_operator.spec.ts
- tests/cypress/latest/fixtures/runtime_test_result.yaml
- tests/cypress/latest/package.json
- tests/cypress/latest/support/commands.ts
- tests/cypress/latest/support/e2e.ts
- Skip tests run on first failure in `@install` using Cypress.Stop()
- Bump Cypress to latest version
- Refactors `providers_setup.spec.ts`
- Remove redundant check in `removeFleetGitRepo`, since repo names are now unique
Fixes #25 
`@install @short` nightly - :green_circle: https://github.com/rancher/rancher-turtles-e2e/actions/runs/14360018165
Tests not skipped if `@short` failure:
`@install @short` - https://github.com/rancher/rancher-turtles-e2e/actions/runs/14360035519
Tests skipped if `@install` failure:
`@install` - https://github.com/rancher/rancher-turtles-e2e/actions/runs/14360856892
`@install @short` - https://github.com/rancher/rancher-turtles-e2e/actions/runs/14360874340
> Stop tests on first failure in @install

- tests/cypress/latest/e2e/unit_tests/turtles_extension.spec.ts
- tests/cypress/latest/e2e/unit_tests/turtles_operator.spec.ts
Uses https for adding capi-ui repo instead of git, now it will be according to turtles documentation. 
This is also an attempt to fix problematic adding of the capi-ui git repo which might be affected by gh rate-limit - adding timeouted after 2mins.
> Switch capi-ui repo to https instead of git

- tests/go.mod
- tests/go.sum
rancher/rancher:v2.10-head is not being released on dockerhub anymore but on stgregistry.
> Testhelpers bump 210

- tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
Just provider versions bump
Testrun on `0.19.0-rc.1`: https://github.com/rancher/rancher-turtles-e2e/actions/runs/14668083102
> Provider versions bump after release v0.19.0-rc.1

- tests/cypress/latest/support/commands.ts
addRepository function will be always refreshing repositories after creating/adding the repo, workaround for https://github.com/rancher/rancher/issues/49671
> Always refresh repo after adding

- .github/workflows/master-e2e.yaml
- tests/assets/rancher-turtles-fleet-example/capa/kubeadm/class-clusters/templates/cluster.yaml
- tests/assets/rancher-turtles-fleet-example/capa/rke2/class-clusters/templates/cluster.yaml
- tests/assets/rancher-turtles-fleet-example/capz/aks/class-clusters/templates/cluster.yaml
- tests/assets/rancher-turtles-fleet-example/capz/kubeadm/class-clusters/templates/cluster.yaml
- tests/assets/rancher-turtles-fleet-example/capz/rke2/class-clusters/templates/cluster.yaml
- tests/cypress/latest/e2e/unit_tests/capa_kubeadm_clusterclass.spec.ts
- tests/cypress/latest/e2e/unit_tests/capa_rke2_clusterclass.spec.ts
- tests/cypress/latest/e2e/unit_tests/capv_kubeadm_clusterclass.spec.ts
- tests/cypress/latest/e2e/unit_tests/capv_rke2_clusterclass.spec.ts
- tests/cypress/latest/e2e/unit_tests/capz_aks_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capz_aks_clusterclass.spec.ts
- tests/cypress/latest/e2e/unit_tests/capz_kubeadm_clusterclass.spec.ts
- tests/cypress/latest/e2e/unit_tests/capz_rke2_clusterclass.spec.ts
- tests/cypress/latest/fixtures/capa-aws-cluster-identity.yaml
- tests/cypress/latest/fixtures/capi-aws-provider.yaml
- tests/cypress/latest/fixtures/capi-azure-provider.yaml
- tests/cypress/latest/fixtures/capi-vsphere-provider.yaml
- tests/cypress/latest/fixtures/capz-azure-cluster-identity.yaml
- tests/cypress/latest/support/commands.ts
- tests/cypress/latest/support/e2e.ts
- Use managed Cluster Identities for Clusterclass tests
- Create CAPIProviders using YAML for above tests with blank credentials
- Change run order of the specs: Clusters > Class-Clusters tests
- Use cluster auto-import label for Clusterclass tests
- Add relevant functions in commands.ts
Fixes #202 , #205 
:green_circle:  [@full](https://github.com/rancher/rancher-turtles-e2e/actions/runs/15860366728), [@vsphere](https://github.com/rancher/rancher-turtles-e2e/actions/runs/15860362451), [@short](https://github.com/rancher/rancher-turtles-e2e/actions/runs/15854246652)
> Use Cluster Identities for Clusterclass tests

- .github/workflows/master-e2e.yaml
- tests/assets/rancher-turtles-fleet-example/capv/rke2/class-clusters/templates/cluster.yaml
- tests/assets/rancher-turtles-fleet-example/capv/rke2/class-clusters/values.yaml
- tests/cypress/latest/e2e/unit_tests/capv_rke2_cluster.spec.ts
- tests/cypress/latest/e2e/unit_tests/capv_rke2_clusterclass.spec.ts
- tests/cypress/latest/fixtures/capv-docker-auth-token-secret.yaml
- tests/cypress/latest/fixtures/capv-helm-values.yaml
- tests/cypress/latest/fixtures/capv-kube-vip-static-pod-toggle-job.yaml
- tests/cypress/latest/support/commands.ts
- tests/cypress/latest/support/e2e.ts
Described in QASE RT case 131https://app.qase.io/project/RT?case=131&suite=18
In addition:
* capv rke2 clusterClass test now provisions HA cluster (3+3)
* new `cy.ImportYaml` function taken from fleet-e2e project - accepts files as well as variable with yaml
* new `cy.verifyResourceCount` for blocking until the resources are available
* capv rke2 clusterClass now uses dockerhub authentication - to preven Rate limit (not doable for simple/legacy rke2)
* Introduced `control_plane_machine_count` and ` worker_machine_count` keys in `capv-helm-values.yaml` - before this change defaults from chart's values.yaml were used.
Fixes #168 #208
* ~new testrun (added namespace selection for importYaml + counting kub-vip pods + fleetaddon bump) …
> CAPV RKE2 kube-vip test

- tests/cypress/latest/e2e/capd_kubeadm_cluster.spec.ts
- tests/cypress/latest/e2e/capd_rke2_cluster.spec.ts
- tests/cypress/latest/e2e/capd_ui_clusterclass.spec.ts
- tests/cypress/latest/e2e/capz_kubeadm_clusterclass.spec.ts
- tests/cypress/latest/e2e/capz_rke2_clusterclass.spec.ts
1. Change indentation to 2 spaces for the files that were missing it.
2. Add and remove clusterclass repo for all the CAPD tests, same as other providers; this will allow successful run of test files without depending upon the order in which they are ran. For e.g. currently if we run `capd_ui_clusterclass.spec.ts` before/without `capd_kubeadm_cluster.spec.ts`, the test will fail since it misses the clusterclass fleet repo addition.
Fixes part of #214
> Add and remove clusterclass fleet repo for all the capd tests

- .github/workflows/master-e2e.yaml
- .github/workflows/ui-e2e.yaml
- tests/cypress/latest/cypress.config.ts
- tests/cypress/latest/e2e/capa_kubeadm_clusterclass.spec.ts
- tests/cypress/latest/e2e/capa_rke2_clusterclass.spec.ts
- tests/cypress/latest/e2e/capd_rke2_clusterclass.spec.ts
- tests/cypress/latest/e2e/capg_kubeadm_clusterclass.spec.ts
- tests/cypress/latest/e2e/capv_kubeadm_clusterclass.spec.ts
- tests/cypress/latest/e2e/capv_rke2_clusterclass.spec.ts
- tests/cypress/latest/e2e/capz_kubeadm_clusterclass.spec.ts
- tests/cypress/latest/e2e/capz_rke2_clusterclass.spec.ts
- tests/cypress/latest/e2e/providers_setup.spec.ts
- tests/cypress/latest/support/commands.ts
- tests/cypress/latest/support/e2e.ts
- tests/scripts/start-cypress-tests
Adding support for rancher 2.12
* Backward compatible with 2.11
* Uses `head/2.12` by default (but 2.11 for upgrade tests)
* Changes provider waiting and matching
* Prevents showing confirmation dialog when deleting resources by clicking while holding Ctrl key
* Usage of HelmApps or HelmOps is driven by installed rancher version
* Changed way how we create namespaces out of projects (new pagination doesn't allow filter out `Not in a Project`)
* checkChart() without refreshing repo when chart is not available
* Fixed browser selection to Chrome + tweaked memory handling and performance
* Specs for cy docker run are comma separated
Fixes #243
* 🟢 `head/2.12 @install @vsphere` [here](https://github.com/rancher/rancher-turtles-e2e/actions/runs/17553898499)
* 🟢 `head/2.12 @install @short` …
> Add support for Rancher 2.12

- .github/workflows/master-e2e.yaml
- .github/workflows/ui-e2e.yaml
- Add build_type input for dev_chart (prime|comunity)
- Had to deprecate `capi_ui_version` input due to limit - 10 inputs for manual workflows 
Fixes #291 
- [@install prime](https://github.com/rancher/rancher-turtles-e2e/actions/runs/18033538979)
- [@install community](https://github.com/rancher/rancher-turtles-e2e/actions/runs/18033281969) (failure expected until https://github.com/rancher/rancher-turtles-e2e/issues/292 is implemented)
> Add build_type input for dev_chart

- tests/cypress/latest/package.json
- tests/cypress/latest/tsconfig.json
* After updating `@cypress/grep` to v5 the types checking for `it` and `describe` enhanced by `tags` stopped to work. Problem was that TypeScript type declarations are now included in the package and loading external types via `types: ["@cypress/grep"]` in `tsconfig.json` is no longer supported and causes TypeScript and/or IntelliSense issues. Removing it from `tsconfig.json` allows TypeScript to correctly load the built-in declarations.
* When doing so I also fixed missing types for `lodash` and `js-yaml` libs by adding them into `package.json`
Initial update to v5 was done here https://github.com/rancher/rancher-turtles-e2e/pull/288
> Fix TS support for tags in it() and describe()

- tests/cypress/latest/support/e2e.ts
- tests/cypress/latest/tsconfig.json
Fixes IntelliSense issues with grep tags - the change will allow loading of the incorporated type definition from `cypress/grep`
Removes also `nuxt/types` which caused problems with opening `{` in tsconfig.json (red underscore).
> Update module resolution to "nodenext" to support Cypress grep tags

- .github/workflows/master-e2e.yaml
- .github/workflows/ui-e2e.yaml
- tests/cypress/latest/e2e/providers_setup.spec.ts
- Bump Rancher version for nightly CI tests, Ref: https://github.com/rancher/turtles/blob/main/charts/rancher-turtles/Chart.yaml#L21
- Temporarily disable providers version check, to be addressed in https://github.com/rancher/rancher-turtles-e2e/issues/303
Fixes #304 
:green_circle:  [2.12 @install @short](https://github.com/rancher/rancher-turtles-e2e/actions/runs/18307404181),
[2.13 @install](https://github.com/rancher/rancher-turtles-e2e/actions/runs/18307411051) (failure expected until https://github.com/rancher/rancher-turtles-e2e/issues/292 is done)
> Bump to Rancher 2.13
